version: 2

models:
  - name: stg_reddit_posts
    description: "Modèle de staging pointant vers la source brute Reddit."
    columns:
      - name: id
        tests:
          - unique
          - not_null

  - name: reddit_posts_cleaned
    description: "Données Reddit nettoyées et dédupliquées (Couche Silver)."
    columns:
      - name: post_id
        tests:
          - unique
          - not_null
      - name: created_at
        tests:
          - not_null
      - name: subreddit
        tests:
          - accepted_values:
              values: ["france", "datascience", "dataengineering", "MachineLearning", "BusinessIntelligence"]
      - name: score
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: -100
              max_value: 1000000

  - name: sentiment_daily_aggregate
    description: "Kpis quotidiens par subreddit (Couche Gold)."
    tests:
      - dbt_utils.at_least_one:
          column_name: total_posts
