reddit_analytics:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth # ou service-account en prod
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "dms_dev" # Préfixe qui sera complété par dbt_project.yml (ex: dms_dev_silver)
      threads: 4
      timeout_seconds: 300
      location: EU
      priority: interactive
    
    ci:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "dms_ci_{{ env_var('GITHUB_RUN_ID', 'local') }}"
      threads: 4
      keyfile: "{{ env_var('GCP_SA_KEY_PATH') }}"
      location: EU
      priority: interactive

    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "dms_prod"
      threads: 8
      keyfile: "{{ env_var('GCP_SA_KEY_PATH') }}"
      location: EU
      priority: batch
